version: '3'

services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:13.4'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microGo
    volumes:
      - mariadb:/var/lib/postgresql/data/

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis:/data

  #  start MariaDB, and ensure that data is stored to a mounted volume
  mariadb:
    image: 'mariadb:10.6'
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microGo
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password
    volumes:
      - postgres:/docker-entrypoint-initdb.d
volumes:
  postgres:
  redis:
  mariadb: