version: '3'

services:
  postgres:
    image: 'postgres'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microGo
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d/

volumes:
  postgres: