name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.17
    
#     - name: Build Render Package
#       working-directory: microGo/render
#       run: go build -v .
      
#     - name: Build session Package
#       working-directory: microGo/session
#       run: go build -v .

#     - name: Test Render Package
#       working-directory: microGo/render
#       run: go test -v .
      
#     - name: Test session Package
#       working-directory: microGo/render
#       run: go test -v .
